version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    container_name: postgres
    ports:
      - '5432:5432'
  app:
    image: node
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    entrypoint: ['./entrypoint.sh']
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db



